app:
  build: .
  #env_file:
  #  - ./env.list
  ports:
    - 80:80
    - 8080:8080
  environment:
    - NODE_ENV=development
  volumes:
    - ./:/var/www
    - /home/reese/npm/:/npm
  command: sleep infinity
  #command: authbind --deep npm run dev
